
#ifndef FMI_OOP_MYSTD_ENABLE_H
#define FMI_OOP_MYSTD_ENABLE_H

#define FMI_OOP_USE_MYSTD_VECTOR
#define FMI_OOP_USE_MYSTD_STRING
// #define FMI_OOP_USE_MYSTD_UNORDERED_MAP

#endif // FMI_OOP_MYSTD_ENABLE_H
